CREATE TABLE `contract_info` (
  `id` varchar(64) NOT NULL,
  `code` varchar(64) NOT NULL,
  `name` varchar(255) NOT NULL,
  `type` varchar(64) DEFAULT NULL,
  `contract_category` varchar(64) DEFAULT NULL,
  `partner_name` varchar(255) DEFAULT NULL,
  `our_side_name` varchar(255) DEFAULT NULL,
  `project_name` varchar(255) DEFAULT NULL,
  `template_name` varchar(255) DEFAULT NULL,
  `amount` decimal(18,2) DEFAULT NULL,
  `currency` varchar(16) DEFAULT 'CNY',
  `tax_rate` decimal(10,2) DEFAULT NULL,
  `status` varchar(64) DEFAULT NULL,
  `approval_stage` varchar(64) DEFAULT NULL,
  `risk_level` varchar(64) DEFAULT NULL,
  `performance_status` varchar(64) DEFAULT NULL,
  `payment_status` varchar(64) DEFAULT NULL,
  `archive_status` varchar(64) DEFAULT NULL,
  `signing_method` varchar(64) DEFAULT NULL,
  `sign_date` date DEFAULT NULL,
  `effective_date` date DEFAULT NULL,
  `expire_date` date DEFAULT NULL,
  `summary` text,
  `remark` text,
  `create_by` varchar(64) DEFAULT NULL,
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP,
  `update_by` varchar(64) DEFAULT NULL,
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `del_flag` char(1) DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_contract_info_code` (`code`),
  KEY `idx_contract_info_partner_name` (`partner_name`),
  KEY `idx_contract_info_status` (`status`),
  KEY `idx_contract_info_expire_date` (`expire_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `contract_approval` (
  `id` varchar(64) NOT NULL,
  `contract_id` varchar(64) NOT NULL,
  `node_name` varchar(128) DEFAULT NULL,
  `assignee_name` varchar(128) DEFAULT NULL,
  `status` varchar(64) DEFAULT NULL,
  `comment` text,
  `handled_time` datetime DEFAULT NULL,
  `sort_no` int DEFAULT 0,
  `create_by` varchar(64) DEFAULT NULL,
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP,
  `update_by` varchar(64) DEFAULT NULL,
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `del_flag` char(1) DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `idx_contract_approval_contract_id` (`contract_id`),
  KEY `idx_contract_approval_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `contract_payment_plan` (
  `id` varchar(64) NOT NULL,
  `contract_id` varchar(64) NOT NULL,
  `phase` varchar(128) DEFAULT NULL,
  `pay_type` varchar(32) DEFAULT NULL,
  `amount` decimal(18,2) DEFAULT NULL,
  `percent_value` decimal(10,2) DEFAULT NULL,
  `plan_date` date DEFAULT NULL,
  `actual_date` date DEFAULT NULL,
  `status` varchar(64) DEFAULT NULL,
  `remark` text,
  `create_by` varchar(64) DEFAULT NULL,
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP,
  `update_by` varchar(64) DEFAULT NULL,
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `del_flag` char(1) DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `idx_contract_payment_plan_contract_id` (`contract_id`),
  KEY `idx_contract_payment_plan_plan_date` (`plan_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `contract_milestone` (
  `id` varchar(64) NOT NULL,
  `contract_id` varchar(64) NOT NULL,
  `name` varchar(255) DEFAULT NULL,
  `owner_name` varchar(128) DEFAULT NULL,
  `due_date` date DEFAULT NULL,
  `status` varchar(64) DEFAULT NULL,
  `remark` text,
  `create_by` varchar(64) DEFAULT NULL,
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP,
  `update_by` varchar(64) DEFAULT NULL,
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `del_flag` char(1) DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `idx_contract_milestone_contract_id` (`contract_id`),
  KEY `idx_contract_milestone_due_date` (`due_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `contract_file` (
  `id` varchar(64) NOT NULL,
  `contract_id` varchar(64) NOT NULL,
  `file_name` varchar(255) DEFAULT NULL,
  `file_type` varchar(64) DEFAULT NULL,
  `storage_type` varchar(32) DEFAULT NULL,
  `storage_path` varchar(512) DEFAULT NULL,
  `file_size` bigint DEFAULT NULL,
  `mime_type` varchar(128) DEFAULT NULL,
  `source_type` varchar(64) DEFAULT NULL,
  `create_by` varchar(64) DEFAULT NULL,
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP,
  `update_by` varchar(64) DEFAULT NULL,
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `del_flag` char(1) DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `idx_contract_file_contract_id` (`contract_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `import_batch` (
  `id` varchar(64) NOT NULL,
  `batch_no` varchar(64) NOT NULL,
  `import_type` varchar(32) DEFAULT NULL,
  `source_file_name` varchar(255) DEFAULT NULL,
  `status` varchar(64) DEFAULT NULL,
  `success_count` int DEFAULT 0,
  `fail_count` int DEFAULT 0,
  `operator_name` varchar(128) DEFAULT NULL,
  `remark` text,
  `create_by` varchar(64) DEFAULT NULL,
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP,
  `update_by` varchar(64) DEFAULT NULL,
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `del_flag` char(1) DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_import_batch_batch_no` (`batch_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `import_record` (
  `id` varchar(64) NOT NULL,
  `batch_id` varchar(64) NOT NULL,
  `record_name` varchar(255) DEFAULT NULL,
  `parsed_payload` json DEFAULT NULL,
  `confirm_status` varchar(64) DEFAULT NULL,
  `target_contract_id` varchar(64) DEFAULT NULL,
  `error_message` text,
  `create_by` varchar(64) DEFAULT NULL,
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP,
  `update_by` varchar(64) DEFAULT NULL,
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `del_flag` char(1) DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `idx_import_record_batch_id` (`batch_id`),
  KEY `idx_import_record_target_contract_id` (`target_contract_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
